name: letterbox
description: A minimal text-only letter app inspired by India Post.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  cloud_firestore: ^4.8.0
  intl: ^0.18.1
  uuid: ^4.5.1
  lottie: ^3.1.2
  flip_card: ^0.7.0
  shared_preferences: ^2.2.2 
  google_fonts: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/letterbox.png
    - assets/postcards/
